### PR TITLE
Telnet: Keep track of telnet negotiation options

### LINKED ISSUE #1908: Telnet option negotiation loop
we are using the ser2net for a gateway between our network and the serial ports. If we use the telnet library to connect to ser2net we see endless IAC DONT/WONT/DO/WILL packets. Both processes run on the same machine and thus eats up the whole CPU.

I did a quick investigation and found out that this might the "nonterminating acknowledgment loop" which is mentioned in the telnet rfc854. I suspect this is because both sides (ser2net and the telnet library) are "dumb" implementations. Eg. they just answer by refusing/acknowledging the option. But the rfc says that:

> ```
>  b. If a party receives what appears to be a request to enter some
>  mode it is already in, the request should not be acknowledged.
>  This non-response is essential to prevent endless loops in the
>  negotiation.  It is required that a response be sent to requests
>  for a change of mode -- even if the mode is not changed.
> ```

Here is a short trace. Please note that this trace was done using the plain telnetlib, not the actual Telnet library.

> ```
>  # this is the initial sequence of ser2net
>  recv '\xff\xfb\x03\xff\xfb\x01\xff\xfe\x01\xff\xfd\x00'
>    IAC WILL 3  # this is the first command from the receive string from above
>  send DONT 3   # (1)
>    IAC WILL 1
>  send DONT 1
>    IAC DONT 1
>  send WONT 1
>    IAC DO 0
>  send WONT 0
>  recv '\xff\xfc\x03'  # (2) ser2net answers to (1)
>    IAC WONT 3
>  send DONT 3  # telnet library answers to (2), etc..
>  recv '\xff\xfc\x01\xff\xfe\x01\xff\xfe\x00'
>    IAC WONT 1
>  send DONT 1
>    IAC DONT 1
>  send WONT 1
>    IAC DONT 0
>  send WONT 0
>  recv '\xff\xfc\x03'
>    IAC WONT 3
>  send DONT 3
>  recv '\xff\xfc\x01\xff\xfe\x01\xff\xfe\x00'
>    IAC WONT 1
>  send DONT 1
>    IAC DONT 1
>  send WONT 1
>    IAC DONT 0
>  send WONT 0
>  recv '\xff\xfc\x03'
>    IAC WONT 3
>  send DONT 3
>  recv '\xff\xfc\x01\xff\xfe\x01\xff\xfe\x00'
>    IAC WONT 1
>  send DONT 1
>    IAC DONT 1
>  send WONT 1
>    IAC DONT 0
>  send WONT 0
>  recv '\xff\xfc\x03'
>    IAC WONT 3
>  send DONT 3
>  recv '\xff\xfc\x01\xff\xfe\x01\xff\xfe\x00'
>    IAC WONT 1
>  send DONT 1
>    IAC DONT 1
>  send WONT 1
>    IAC DONT 0
>  send WONT 0
>  [..]
> ```

### PR DESCRIPTION
**Pull request by mwalle**
To prevent endless negotiation loops with the telnet options, we must not
reply to already negotiated options.

### CODE REVIEW

**Comment by robotci** [comment]
Admin, can CI be enabled?

**Comment by mwalle** [comment]
unfortunately, i cannot provide a test case because this is too low level and doesn't fit into the "use a telnet server as test partner" method.

**Comment by jussimalinen** [comment]
Looks good. Automatic test is too difficult probably, so we dont need to bother with that.

Could we just do this to simplify the code a bit:

```python

if cmd in (telnetlib.DO, telnetlib.DONT, telnetlin.WILL, telnetlib.WONT):
            if (cmd, opt) in self._opt_responses:
                return
            self._opt_responses.add((cmd, opt))

```

**Comment by pekkaklarck** [comment]
@mwalle, any comments to comment by @jussimalinen? This looks trivial enough to still be included into RF 2.9 alpha 1.

**Comment by mwalle** [comment]
sorry for the late response, i've some private matters atm.

anyway. yes, looks good, i've pushed a new version.

**Comment by jussimalinen** [comment]
Excellent. I'm including this to alpha1 then after all

**Pull request merged**
