### PR TITLE
fix #2548

### LINKED ISSUE #2548: `rebot --merge` doesn't work correctly if test messages contain HTML
looks like the same root cause as in #2360 i.e. the "Re-executed test has been merged." comes before the \*HTML\* marker

Assume `dummy.robot`:
```
*** Settings ***
Test Teardown    TcTeardown
*** Test Cases ***
TC
    Fail Execution    this fails
*** Keywords ***
TcTeardown
    Set Test Message   *HTML*<a href="http://robotframework.org/">rf</a>
```
Run:
`pybot -o o1.xml dummy.robot` --> parsed as HTML in report.html
`pybot -R o1.xml -o o2.xml dummy.robot` --> parsed as HTML in report.html
`rebot --merge o1.xml o2.xml` --> no parsing i.e. report shows the raw HTML tags

### PR DESCRIPTION
**Pull request by yahman72**
Merge messages are now always HTML.

changes tested with rebot acceptance tests (Python v2.7 & Windows 10)
```
> python atest/run.py python atest\robot\rebot
Running command:
C:\Python27\python.exe C:\git\fork-rf\src\robot\run.py --doc Robot Framework acceptance tests --metadata interpreter:Python 2.7 on Windows --variablefile C:\git\fork-rf\atest\interpreter.py;python;Python;2.7 --pythonpath C:\git\fork-rf\atest\resources --outputdir C:\git\fork-rf\atest\results\Python-2.7-Windows --splitlog --console dotted --consolewidth 100 --SuiteStatLevel 3 --TagStatExclude no-* --exclude require-python26 --exclude require-jython --exclude require-ipy --exclude no-py2 --exclude no-windows atest\robot\rebot

Running suite 'Rebot' with 55 tests.
====================================================================================================
.......................................................
====================================================================================================
Run suite 'Rebot' with 55 tests in 29 seconds 35 milliseconds.

PASSED
55 critical tests, 55 passed, 0 failed
55 tests total, 55 passed, 0 failed

Output:  C:\git\fork-rf\atest\results\Python-2.7-Windows\output.xml
Log:     C:\git\fork-rf\atest\results\Python-2.7-Windows\log.html
Report:  C:\git\fork-rf\atest\results\Python-2.7-Windows\report.html
```

### CODE REVIEW

**Comment by yahman72** [comment]
results:
```
> python atest/run.py python atest\robot\rebot\
Running command:
C:\ta\virtualenv\rf3.0.3\Scripts\python.exe C:\git\fork-rf\src\robot\run.py --doc Robot Framework acceptance tests --metadata interpreter:Python 2.7 on Windows --variablefile C:\git\fork-rf\atest\interpreter.py;python;Python;2.7 --pythonpath C:\git\fork-rf\atest\resources --outputdir C:\git\fork-rf\atest\results\Python-2.7-Windows --splitlog --console dotted --consolewidth 100 --SuiteStatLevel 3 --TagStatExclude no-* --exclude require-python26 --exclude require-jython --exclude require-ipy --exclude no-py2 --exclude no-windows atest\robot\rebot\

Running suite 'Rebot' with 56 tests.
====================================================================================================
........................................................
====================================================================================================
Run suite 'Rebot' with 56 tests in 25 seconds 691 milliseconds.

PASSED
56 critical tests, 56 passed, 0 failed
56 tests total, 56 passed, 0 failed

Output:  C:\git\fork-rf\atest\results\Python-2.7-Windows\output.xml
Log:     C:\git\fork-rf\atest\results\Python-2.7-Windows\log.html
Report:  C:\git\fork-rf\atest\results\Python-2.7-Windows\report.html
```

**Comment by yahman72** [comment]
Old:
image

New - merged re-execution:
image

New - merged re-re-execution:
image

**Comment by yahman72** [comment]
forgot to push the last updates in Friday's sprint - now this should be complete.

**Comment by yahman72** [comment]
all rebot tests passing:
```
> python atest/run.py python atest\robot\rebot\
Running command:
C:\ta\virtualenv\rf3.0.3\Scripts\python.exe C:\git\fork-rf\src\robot\run.py --doc Robot Framework acceptance tests --metadata interpreter:Python 2.7 on Windows --variablefile C:\git\fork-rf\atest\interpreter.py;python;Python;2.7 --pythonpath C:\git\fork-rf\atest\resources --outputdir C:\git\fork-rf\atest\results\Python-2.7-Windows --splitlog --console dotted --consolewidth 100 --SuiteStatLevel 3 --TagStatExclude no-* --exclude require-python26 --exclude require-jython --exclude require-ipy --exclude no-py2 --exclude no-windows atest\robot\rebot\

Running suite 'Rebot' with 56 tests.
====================================================================================================
........................................................
====================================================================================================
Run suite 'Rebot' with 56 tests in 29 seconds 393 milliseconds.

PASSED
56 critical tests, 56 passed, 0 failed
56 tests total, 56 passed, 0 failed

Output:  C:\git\fork-rf\atest\results\Python-2.7-Windows\output.xml
Log:     C:\git\fork-rf\atest\results\Python-2.7-Windows\log.html
Report:  C:\git\fork-rf\atest\results\Python-2.7-Windows\report.html

(rf3.0.3) [20.01.2018 12:20:19 C:\git\fork-rf\]
```

**Comment by pekkaklarck** [comment]
Sorry for not reviewing this yet. Been rather busy lately and soon leaving for a holiday. Should have time to really concentrate on RF development after that.

**Comment by pekkaklarck** [comment]
Finally had time for a review and for RF development in general. The PR looks good and ready to be merged. I may do a little cleanup to code and tests afterwards.

**Pull request merged**
