### PR TITLE
Tidy rows longer than 80 chars to separate rows in plain text files

### PR DESCRIPTION
**Pull request by guykisel**
#1891 

I would prefer to make the max length a Tidy command line option, but I would have to make a lot of changes to pass that value all the way down to `rowsplitter`. It seems a lot simpler to just set a max character count in `TxtFormatter` and pass that into `rowsplitter`. I would also prefer to pass the column separator into `rowsplitter` for use in calculating the row length, but there doesn't seem to be a simple way to do that in the current structure. Assuming the separator is four spaces seems to work well enough.

### CODE REVIEW

**Comment by robotci** [comment]
Tests passed.



Refer to this link for build results (access rights to CI server needed): 
http://robot.radiaatto.ri.fi//job/RobotFramework-pull-requests/59/Tests passed.

**Comment by jussimalinen** [comment]
Thanks for the pull request! The idea seems very good, but when discussing this with @pekkaklarck we thought this probably be configurable from the command line..

We cant take this into 2.8.7 anymore (planning release for Tomorrow), but lets look at this for 2.9.

**Comment by guykisel** [comment]
Sure, sounds good.

**Comment by guykisel** [comment]
Note this is a work in progress as I update this PR to reflect the latest changes in master and also try to make this configurable from the command line.

**Comment by robotci** [comment]
Tests FAILED!


Refer to this link for build results (access rights to CI server needed): 
http://robot.radiaatto.ri.fi//job/RobotFramework-pull-requests/64/Tests FAILED!

**Comment by robotci** [comment]
Tests FAILED!


Refer to this link for build results (access rights to CI server needed): 
http://robot.radiaatto.ri.fi//job/RobotFramework-pull-requests/65/Tests FAILED!

**Comment by pekkaklarck** [comment]
Sorry for not looking at this PR earlier. What's the current status?

**Comment by guykisel** [comment]
Haven't looked at this in a few weeks. Making it configurable from the command line is a bit difficult due to how deeply nested the rowsplitter is. I need to spend more time looking at the structure of the relevant code and thinking about it.

**Comment by pekkaklarck** [comment]
Yeah, the related code seems to be a bit too clever. Let me know if you want to discuss it e.g. on IRC some day. Before a major release we can do even larger refactoring if needed.

**Comment by guykisel** [comment]
Sure, that could be good. My schedule is a bit uncertain for the next few weeks, so I might not be able to have a live discussion for a while. I don't think this is a high priority enhancement, since I doubt Tidy is heavily used.

**Comment by richcocoa** [comment]
I would like to work on this. May I pick it up if it is not being worked on?

**Comment by pekkaklarck** [comment]
Please go ahead!

**Comment by fabo-at-noona** [comment]
there was PR#2771 which has been closed last week since **nobody** reviewed it.

**Comment by pekkaklarck** [comment]
Tidy has been totally rewritten as part of RF 3.2 parser rewrite and there is not way this PR could anymore be merged. Good news is that the new Tidy is a lot better to enhance if needed.

**Pull request closed without merging**
