### PR TITLE
Issue 3651: String: `Should Be Tittle Case` is not consistent with `C…

### PR DESCRIPTION
**Pull request by miktuy**
Try to fix bug by using keyword ```convert_to_title_case``` internal
image

### CODE REVIEW

**Comment by pekkaklarck** [comment]
Thanks for PR! The new functionality needs tests and we perhaps should also think what's the best way to handle bytes.

**Comment by pekkaklarck** [comment]
I already earlier mentioned that this new functionality would need tests. I looked at the changes a bit more thoroughly and noticed that documentation is somewhat misleading especially related to the `exclude` argument. The docs should also mention that the logic has changed in RF 4.0. Are you @miktuy interested to continue with this PR or should I fix the aforementioned issues?

**Comment by miktuy** [comment]
Sorry. I couldn't find time to fix this issue totally(

**Comment by pekkaklarck** [comment]
Ok, no problem.

**Pull request closed without merging**
