### PR TITLE
Enum conversion with normalized names. Implements #3611

### PR DESCRIPTION
**Pull request by willemvanoort**
I have implemented the enhancement proposed in issue #3611. The changes are backwards compatible as the member is first matched without normalization.

### CODE REVIEW

**Comment by willemvanoort** [comment]
Not sure why "Acceptance tests (CPython + PyPy) / Python 3.7 on ubuntu-latest (pull_request)" has failed here.

**Comment by pekkaklarck** [comment]
Quick comments on mobile:
- Code changes look good. First trying the exact march is a good idea.
- This new functionality needs to be tested.
- Something is needed in the User Guide as well.
- Don't know why tests fail, could be something unrelated as well, and cannot check right now.

**Comment by pekkaklarck** [comment]
Looking very good. Two minor things to do, though:

- Would be good to add a test that using `BAR` matches member `BAR` even if there would be members like `bar` or `B_A_R`.
- User Guide doc needs a note that case/space/underscore insensitivity is new in RF 3.2.1. Could either add `Starting from RF 3.2.1` before the newly added text or add a separate note about that elsewhere.

Do you @willemvanoort want to do the above or should I just merge this PR now and do them myself?

**Comment by willemvanoort** [comment]
Updated last commit with the minors. One thing that I realized when updating the tests is that in python27 dir(Enum) is called to collect enum members, alphabetizing the members, whereas in python3 the Enum.__members__ property is read, which returns an OrderedDict (in the order of definition). Hence, conversion might in some very specific cases return a different member when running in different environments. Just dropping this here in case you'd want to smooth this out.

**Comment by pekkaklarck** [comment]
In my opinion it's important, and enough, if exact match matches the correct member. I doubt it's common to have members with names that have same normalized form and if you do, it's better to then use exact arguments anyway. Having members like `FOO` and `foo` and then using `Foo` doesn't make much sense.

The PR looks very good and I'll merge it. Tests seem to cover everything important, but there could bel separate tests for normalized member matching. This goes to nitpicking so I'll split these tests myself. :smile: 

Thanks for the PR!

**Comment by pekkaklarck** [comment]
After thinking this a bit more, decided to make it an error to use a non-exact match if there are multiple members with same normalized name. Explicit is better than implicit.

**Pull request merged**
