### PR TITLE
#2703 "Lists should be equal" keywords in the Collection library should have the option to ignore order 

### PR DESCRIPTION
**Pull request by bbpatel2001**

### CODE REVIEW

**Comment by bbpatel2001** [comment]
------------------------------------------------------------------------------
Lists Should Be Equal With Different Values Ignore_order :: FAIL L... | PASS |
------------------------------------------------------------------------------
Lists Should Be Equal With Different Values And Own Error Message ... | PASS |
------------------------------------------------------------------------------
Lists Should Be Equal With Different Values And Own And Default Er... | PASS |
------------------------------------------------------------------------------
Lists Should Be Equal With Named Indices As List Ignore_order :: F... | FAIL |
Lists are different:
Index 0 (a): 11 != 13
Index 2 (c): 13 != 11
------------------------------------------------------------------------------
Lists Should Be Equal With Named Indices As List With Too Few Valu... | PASS |
------------------------------------------------------------------------------
Lists Should Be Equal With Duplicate Value Ignore_order :: PASS li... | PASS |
------------------------------------------------------------------------------
Lists Should Be Equal With Duplicate Value Second Small List :: FA... | FAIL |
Lists  are  different
------------------------------------------------------------------------------
Lists Should Be Equal With Two Duplicate Value Ignore_order :: FAI... | PASS |
------------------------------------------------------------------------------
Lists Should Be Equal With Duplicate And Different Value Ignore_or... | FAIL |
Lists are different:
Index 2: A != E
Index 3: D != A

**Comment by bbpatel2001** [comment]
@pekkaklarck , any suggestions   on this ?

**Comment by bbpatel2001** [comment]
@pekkaklarck can you please check this is acceptable PR?

**Comment by kblomqvist** [comment]
Would `List Should Contain Sub List    ${list1}    ${list2}` work for you? It fails if not all of the elements in `list2` are found in `list1`. The order of values and the number of values are not taken into account.

**Pull request closed without merging**
