### PR TITLE
run "Import Resource" keyword with dryrun option

### PR DESCRIPTION
**Pull request by wendi616**
The commit aims to fix this issue https://github.com/robotframework/robotframework/issues/3418.

The keywords can not be found with --dryrun option if they are declared in resource file and loaded by "Import Resource" keyword. I see that the "Import Library" can be executed in dryrun, so please review that we can do the same handling for "Import Resource" keyword.

### CODE REVIEW

**Review by xtereric — COMMENTED** [review]
Looks good to me. Please merge!

**Comment by pekkaklarck** [comment]
Have you tested that the change works as expected in your use case? If it does, we can merge it, but before that there need to be some acceptance tests. If you are new to Robot's acceptance test system, see the `atest/README.rst`. If you still have questions, ping me on the #devel channel on our Slack.

**Comment by wendi616** [comment]
> Have you tested that the change works as expected in your use case? If it does, we can merge it, but before that there need to be some acceptance tests. If you are new to Robot's acceptance test system, see the `atest/README.rst`. If you still have questions, ping me on the #devel channel on our Slack.

**Comment by wendi616** [comment]
Hi @pekkaklarck, Yes, I have already verified it, it works well as expect. and I just upload the acceptance test for this change, would you please help to review it? Thanks a lot!

**Comment by wendi616** [comment]
Hi @pekkaklarck , I accidentally closed it, can you help me reopen it？ Thannk you!

**Comment by wendi616** [comment]
Hi @pekkaklarck , I accidentally closed it, can you help me reopen it？ Thannk you!

**Comment by pekkaklarck** [comment]
Looks good to me! Possibly the test could be added to an existing suite, but I can see is there a suitable place somewhere myself.

**Pull request merged**
