### PR TITLE
strip_spaces parameter added to implement FR 3240

### PR DESCRIPTION
**Pull request by vokiput**
https://github.com/robotframework/robotframework/issues/3240

### CODE REVIEW

**Comment by pekkaklarck** [comment]
This PR seems to be some how messed up right now. When looking at the [changed files](https://github.com/robotframework/robotframework/pull/3583/files), there are lot of unrelated changes. Has something gone wrong when merging changes from the master or what's going on?

**Comment by vokiput** [comment]
The PR was good back in May but now it shows some differences I didn' make.
I resolved 1 conflict it had.
It also shows some changes like .github/workflows/acceptance_tests_cpython.yml which I didn't make.
Feel free to accept this PR or close it. I will create a new one for the next release in case it will be closed.

**Comment by pekkaklarck** [comment]
I cannot merge this PR in the current state. I'll leave it to you to decide do you want to fix the PR or create a new one.

**Comment by vokiput** [comment]
I am going to create a new PR and will try to do it correctly. Close this one for now.

**Comment by pekkaklarck** [comment]
Did you create a new PR?

**Comment by vokiput** [comment]
Hi @pekkaklarck ,
Sorry, I didn't have a chance to create a new PR. Feel free to proceed with a new version.
I'll do my best to apply my changes to the current master next week.
I think I know why my previous PR was spoiled.
I forked the master but didn't configure properly it to sync from upstream.
I hope my next PR will be "luckier"

**Pull request closed without merging**
