### PR TITLE
Fix incorrect suite teardown display position in log.html

### PR DESCRIPTION
**Pull request by jnhyperion**
Suite teardown should be dislpayed in the end of current suite block.

### CODE REVIEW

**Comment by jnhyperion** [comment]
Before fix:
Screen Shot 2020-06-20 at 4 36 08 PM

After fix:
Screen Shot 2020-06-20 at 4 36 39 PM

**Comment by Snooz82** [comment]
I like this.
Would be nice to get thin into 3.2.2

**Comment by pekkaklarck** [comment]
The current behavior is by design. If suite teardown is in its correct chronological position, it is nit seen when you look at the general suite info on top. I don't want to change that.

This has been discussed earlier few times and someone once proposed making this configurable with a cli option. I personally don't think that's worth the effort and I'm also little concerned that lot if configuration options increase complexity. That said, if someone provides a PR making this configurable I'd be happy to merge it. The first step would be submitting an issue about it.

**Comment by pekkaklarck** [comment]
I would also expect implementation ro be a lot simpler. I didn't look the code now, but simply modifying suite template in log.html ought to be enough.

**Comment by jnhyperion** [comment]
@pekkaklarck you're right, we have some similar issue for `TRACE` log: https://github.com/robotframework/robotframework/issues/2086

We should use a unified solution to fix them, my PR can only fix suite teardown which is not good enough.

I'll close my PR.

**Comment by pekkaklarck** [comment]
Relative order of keywords and messages being wrong (#2086) is simply a bug and needs to be fixed (but is hard to). Suite teardown being shown at the top along with other suite information is by design.

**Pull request closed without merging**
