### PR TITLE
Fixes Selenium2Library to SeleniumLibrary in External libraries chapter

### PR DESCRIPTION
**Pull request by aaltat**

### CODE REVIEW

**Comment by pekkaklarck** [comment]
- The related link should also be updated.
- Did you check are there other references to S2L in Robot's code base?

**Comment by aaltat** [comment]
1) Will fix the link too
2) I didn't check in any other places in the user guide. I did run into this by accident. But will check out.

**Comment by aaltat** [comment]
Did use `pss` to find occurrences of Selenium2Library from the user guide and fixed them to SeleniumLibrary.

**Comment by pekkaklarck** [comment]
Thanks!

**Pull request merged**
