### PR TITLE
Adds Portuguese pt-pt translations.

### PR DESCRIPTION
**Pull request by HelioGuilherme66**
Tests are failing because of three words values.

@pekkaklarck In the cases we have an article there will be three words, and seems the parser is not linking it ;)

I tried the pt-pt variant and it was not accepted. Will the pt-br be accepted, for the class PtBr?

Example: 
Test Cases --> Cases of Test --> Casos de Teste

### CODE REVIEW

**Comment by HelioGuilherme66** [comment]
I used Fedora 36 and Python 3.10.5.

**Comment by pekkaklarck** [comment]
Could you test does using "Casos De Teste" work?

**Comment by pekkaklarck** [comment]
The problem with `Casos de Teste` was that it wasn't in title case. I changed to code so that also this format works.

PT is added by #4377 along with other languages so I'll close this PR. Need to think should we add tests for translations like this PR did, though.

**Comment by pekkaklarck** [comment]
My fix above didn't actually fix the problem with headers, it fixed it only with setting names. Better fix coming soon. See #4411 for details.

**Pull request closed without merging**
