### PR TITLE
Extract BDD-style ignored prefixes to a constant

### PR DESCRIPTION
**Pull request by neithere**
As a Developer who uses Robot Framework,
I want the BDD prefixes as a constant
In order to easily monkey-patch it and introduce my own prefixes.

### CODE REVIEW

**Comment by robotci** [comment]
Admin, can CI be enabled?

**Comment by pekkaklarck** [comment]
I don't see any harm accepting this PR, but there's a very serious risk that the related code will be at least partly rewritten in RF 3.0. That obviously wouldn't be good for the possible monkeypatches or other extensions.

Would you be interested in making BDD prefixes officially configurable? We already have issue #519 about that and it would be a great enhancement in RF 3.0.

**Comment by neithere** [comment]
Monkey-patching is generally unreliable, so this PR was intended to enable a moderate hack in the absence of a proper solution. Currently we have to monkey-patch the whole `Namespace._get_bdd_style_handler()` method to enable things like "When I click button" directly via "Click button" keyword. If the next release brings configurable prefixes, I would be happy to remove the hack from our project-specific library.

Concerning #519: it sounds very promising but as I understand it still awaits design decisions, right? I don't see how I would estimate total effort at this point.

**Comment by pekkaklarck** [comment]
If you are interested, I'd be happy to discuss design related to #519. We can use issue comments or perhaps chat on IRC or Slack.

**Comment by bhirsz** [comment]
@pekkaklarck I believe we can close this PR since 5.1 will allow using BDD in other languages (and it's kind of connected to this PR).

**Comment by pekkaklarck** [comment]
True, this is covered by #519 that's already closed.

**Pull request closed without merging**
