### PR TITLE
Add skip console highlighting.

### PR DESCRIPTION
**Pull request by windelbouwman**
Regarding the long open issue about skipping tests, maybe this might be an approach to break up the changes in easily reviewable pieces.

This work contains highlighting on the console for skipped tests only.

### CODE REVIEW

**Comment by windelbouwman** [comment]
@pekkaklarck do you think this change is a good idea? Or do you prefer the work in one big chunk?

**Comment by pekkaklarck** [comment]
Does this change have any effect?

**Comment by pekkaklarck** [comment]
I definitely don't want to add unused code to the master.

**Comment by windelbouwman** [comment]
Okay, let me re-phrase. At the moment, this code is unused. In future, this will be used when the SKIP status is added.

**Comment by windelbouwman** [comment]
I added some more changes that include adding the SKIP status.

**Comment by pekkaklarck** [comment]
I don't want to add code to master that's not used regardless would be used in the future or not. Especially not when it's unclear if/when it is actually used and how would it be used. Such code could be added to a feature branch, but absolutely not to master.

**Comment by windelbouwman** [comment]
Okay, I understand.

**Pull request closed without merging**
