### PR TITLE
Update ListenerInterface.rst

### PR DESCRIPTION
**Pull request by Tset-Noitamotua**
After running into issue #2383 I suggest this little enhancement of corresponding user guide section.

### CODE REVIEW

**Comment by pekkaklarck** [comment]
You are right that docs about taking listeners into use could be enhanced, but I don't think a new listener example is needed. Wouldn't it be enough to just explain, with an example, how to take the next listener example into use? Notice also that there's a separate "Taking listeners into use" section that should probably be referenced from these examples and possibly enhanced too.

**Comment by Tset-Noitamotua** [comment]
- [ ] review PR @me

**Comment by Tset-Noitamotua** [comment]
Is it not possible to assign a task to oneself?

**Comment by pekkaklarck** [comment]
What did you try to do?

**Comment by Tset-Noitamotua** [comment]
@pekkaklarck : I wanted to assign the task 'to review my own PR' to myself here on Github so that I dont forget it later but that is not possible nor is it possible to mark a notification as 'unread' to keep track of it.

**Pull request closed without merging**
