### PR TITLE
Unit tests & acceptance runs using Github Actions - Option 1

### PR DESCRIPTION
**Pull request by tysonite**
I was just interested in Github Actions, and some project with complex requirements for testing. This is mostly based on work done [here](https://github.com/robotframework/robotframework/issues/3275#issuecomment-531652435), and probably can fit into #3275. There are some issues with running tests on Windows Server platform: might be due misconfiguration of environment, or incorrect Python interpreter versions.

You can see the results of the CI run on [this](https://github.com/tysonite/robotframework/actions) page.

More information about Github Actions can be found [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions).

### CODE REVIEW

**Comment by MaciejWiczk** [comment]
Awesome work! Great to see Actions in action with rfwk :)

**Comment by pekkaklarck** [comment]
I have no previous experience with GitHub Actions but this looks great! Do I get it right that Actions allow all kind of automation on GitHub and one of the main usages is CI?

I looked at the [CI results](https://github.com/tysonite/robotframework/actions) and list of provided OSes and Python interpreters is pretty awesome. It seems everything we support is covered. A related issue is that there are lot of failed CI runs, especially on Windows, and debugging/fixing them is not a small task. Is someone interested to look at them with me? On a quick look some look easy to fix and I think I know the root cause for Windows failures as well.

Some general questions about this CI solution:

- Are results somehow shown on the project main page?

- Can we have different jobs so that tests are run with some interpreters after every commit (preferably with a small grace period) and with others twice a day (if there are changes) or something like that?

- Is it possible to force a test run without a commit?

- Is there any way to get access to the generated logs and reports? Debugging failures when you only see the console output is not easy, especially if the problem only occurs on CI and not on your local machine.

**Comment by tysonite** [comment]
1. There is a way to show a badge with a status on a page you want via editing Markdown file (e.g. README.md).
    Example of badge for the workflow being discussed here: 

     The link to such picture looks like that: `https://github.com/tysonite/robotframework/workflows/Unit%20&%20Acceptance%20tests/badge.svg`

     Some details in official [docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository).

2. Yes, this is possible to configure workflows as you wish: trigger jobs on events, schedule them, and much more. As well, you can have multiple separate workflows. See [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows) and [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onschedule). And basic concepts are defined [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/core-concepts-for-github-actions).

3. It is possible for the particular job that has been executed before. The top right corner if you select a particular [workflow](https://github.com/tysonite/robotframework/commit/f059234b96ea3f548b8ed33982c84dc9b28440d9/checks?check_suite_id=323927847):
image

    But I suspect it will run for the same commit as previously.

4. Any artifacts can be uploaded as a result of job. Just need to specify paths to files correctly in YAML workflow file.
    
    image

Going back to the first question, I don't feel I would be able to support fixing of issues on various platforms due to my limited knowledge of Python. But I could defenetely support further changes to workflows, only need to specify requirements more specifically.

**Comment by cclauss** [comment]
My preference would be that we land this PR as is _before_ more changes are made.

**Comment by tysonite** [comment]
@cclauss I feel that #3390 is a better option as acceptance tests run takes a long time to complete. Unit tests can be run on push / pull request events (only around 5-9 minutes to complete), and acceptance tests can be run on pull request / schedule events only.

**Comment by tysonite** [comment]
@pekkaklarck, it would be nice to get more feedback from you. So far I shared 2 options as PRs:
- Current PR (probably requires some additional tweaks in Github Actions workflow files similar to some fixes in #3390)
- #3390 - another option, which looks better from my perspective.
   - [this link](https://github.com/tysonite/robotframework/actions?query=branch%3Agh_tests) points to already happened runs on 2nd option

Anything you would like to change from workflows perspective? If something is unclear, I will try to search for an answer.

**Comment by testautomation** [comment]
RF + CI services like Github Action and CircleCI etc. give great possibility for parallel test execution. @tysonite You can get some inspiration from my CirclieCI pipeline for another open source project. The configuration in YAML format is very similar.

The idea is simply to split the execution (i.e. by test suites or tags) and have separate jobs for each part. At the end use **rebot** to merge the results output into one log/report.html 

https://circleci.com/workflow-run/e1406d12-aeba-403e-b9f4-f38f31fcb9d0

image


config.yml --> https://github.com/ehrbase/ehrbase/blob/develop/.circleci/config.yml

log/report.html as artifacts --> https://circleci.com/gh/ehrbase/ehrbase/1688#artifacts/containers/0
@pekkaklarck  same feature is supported by Github Actions. 

image

One could even push the result htmls to a separate repository and host this as Github Pages. And if one like to get even more creative one could combine that with Shiva's RF-Metrics library and host some really nice Dashboard as static Github Pages which would be automatically updated after each build on master branch :wink: 
Another idea (that I already implemented for above project) is to push the rf-metrics report to a Slack channel :sunglasses:

This is how the Slack message looked (but that could also be static html hosted as Github Pages)
image

Just got another cool idea: the Slack solution is based on doing a screenshot with Selenium-Library in a headless browser in CI. Instead of sending that screenshot to Slack one could push it to RF's repository and have a image link reference in README.md (either in project root or in tests readme).

**Comment by testautomation** [comment]
found my experiments on RF atests on CircleCI --> https://circleci.com/workflow-run/e88f8f30-2a39-40e6-9cba-e5bdaf0c5c1c

https://github.com/Tset-Noitamotua/robotframework/blob/feature/CircleCI-Pipeline/.circleci/config.yml

Basic idea of RFs atests run in parallel

```yaml
robotframework_atests:
    jobs:
      - run unit test
      - run atest cli:
          requires:
            - run unit test
      - run atest core:
          requires:
            - run unit test
      - run atest external:
          requires:
            - run unit test
      - run atest keywords:
          requires:
            - run unit test
      - run atest output:
          requires:
            - run unit test
      - run atest rebot:
          requires:
            - run unit test
      - run atest rpa:
          requires:
            - run unit test
      - run atest running:
          requires:
            - run unit test
      - run atest standard libraries:
          requires:
            - run unit test
``

**Comment by pekkaklarck** [comment]
Quick comments and questions:

- This looks awesome in general!
- Unfortunately my knowledge about these solutions is pretty limited and so is the time I have available. It is thus impossible for me to evaluate different solutions like this PR, #3390, and Circle CI recommended above.
- Luckily there are others in our local Robot Framework community (also members of Robot Framework Foundation) that know this stuff better and who can help with reviewing different options and setting up CI in general. I've already discussed with some of them and they promised to help.
- I definitely want to get this implemented one way or the other. I'll submit a separate issue about setting up CI where we can continue discussion about the overall topic. I'll also summon up those "trusted souls" that can hopefully help drive this forward.
- I'd be more than happy to help fixing tests on different environments. Tests that turn out to be hard/impossible to fix can be easily excluded by using tags.
- Probably good to start with easy environments and start adding others one-by-one to avoid having lot of failing rungs.

**Pull request closed without merging**
