### PR TITLE
Fixed TEST_MESSAGE not reacting to SetTestMessage

### PR DESCRIPTION
**Pull request by osjc**
This is a resurrection of https://github.com/robotframework/robotframework/pull/2189 which was killed by GitHub's reaction to an attempt to amend the commit based on the comments made in the original pull request.

### CODE REVIEW

**Comment by robotci** [comment]
Admin, can CI be enabled?

**Comment by osjc** [comment]
Yes.

**Comment by osjc** [comment]
Line 2817 was fixed to use the correct variable setting method. I also found out that the variable should be set only when the test is in the teardown phrase because that is the time when it gets created. The test was merged into the CI properly (now when I finally managed to decipher the message from atest/README.rst with the help of pekkaklarck, maybe I shall take a look at this as well, the "Test data" needs a bit of expanding as the tests here work quite differently from what a seasoned Robot Framework user would normally expect but I understand why given the fact that behavior during test failures needs to be tested as well). This merging was where I found the bug with the missing IF. Now the acceptance tests run the new test as well and they are passing.

**Comment by jussimalinen** [comment]
robotci: once

**Comment by robotci** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://robot.radiaatto.ri.fi//job/RobotFramework-pull-requests/105/

**Comment by jussimalinen** [comment]
Hmm, there seems to be some configuration problem on the CI.

**Comment by jussimalinen** [comment]
The tests are passing and they look good to me with the changes.

**Comment by jussimalinen** [comment]
Thanks!

**Comment by jussimalinen** [comment]
I will add you to contributors if that is okay.

**Comment by osjc** [comment]
To jussimalinen: Of course it is okay to add me to contributors.

**Pull request merged**
