### PR TITLE
Add thai language

### PR DESCRIPTION
**Pull request by up1**
Add thai language to language file

### CODE REVIEW

**Comment by pekkaklarck** [comment]
Thanks for the translations @up1! There was a conflict because I merged Polish translations first. Can you check that I didn't accidentally break anything when resolving the conflict?

We have used [Crowdin](https://robotframework.crowdin.com/robot-framework) as a collaboration platform for translations. What do you @leeuwe think, should Thai be added there as well?

**Comment by up1** [comment]
> Thanks for the translations @up1! There was a conflict because I merged Polish translations first. Can you check that I didn't accidentally break anything when resolving the conflict?
> 
> We have used [Crowdin](https://robotframework.crowdin.com/robot-framework) as a collaboration platform for translations. What do you @leeuwe think, should Thai be added there as well?

ok, i will check and merge again.

thank you.

**Comment by pekkaklarck** [comment]
No need for another merge. I already resolved the conflict and merged changes. It would just be good if you could verify that results at https://github.com/robotframework/robotframework/blob/master/src/robot/conf/languages.py look good.

**Comment by leeuwe** [comment]
@up1 I've converted your addition to [crowdin](https://robotframework.crowdin.com/translate/ddd00e482856bb264959ae8e3d51e4b6/34/en-th/). It would be great if you can review if I didn't make any mistakes

**Comment by up1** [comment]
> @up1 I've converted your addition to [crowdin](https://robotframework.crowdin.com/translate/ddd00e482856bb264959ae8e3d51e4b6/34/en-th/). It would be great if you can review if I didn't make any mistakes

thank you

**Pull request merged**
