### PR TITLE
[enhancement-2471] update matcher to support more glob-like pattern

### PR DESCRIPTION
**Pull request by nottyo**
I added my code to RF for #2471 issue to support more glob like patterns (test filtering) I referenced the glob-like patterns from the Wiki page https://en.wikipedia.org/wiki/Glob_(programming). Unit tests and acceptance tests are also included in this commit. So please review and if you have any concern, feel free to let me know.

### CODE REVIEW

**Comment by pekkaklarck** [comment]
Finally working with RF 3.1 and finally having time to really look at this PR. Changes to code as well as the added tests and documentation look very good.

While running all tests with the changes I noticed few problems, though. They are listed below and because most of them aren't exactly related to this change I can take care of fixing them myself.

- [ ] Lot of our acceptance tests use `Should Match` with patterns containing brackets (e.g. `[ ERROR ] Error occurred: *`) and these obviously fail now. Need to fix them by using some other keyword or escaping `[` and `]` with a question mark (e.g. `? ERROR ? Error occurred: *`).

- [ ] Old implementation apparently was buggy and considered `foo` to be match `foo\n` even when matching was space-insensitive. The new implementation fixes that, and as a result even more of our acceptance tests fail. They can be easily fixed, but we also need to submit an issue about this problem and add explicit tests for it.

- [ ] Some unit tests are broken due to new tests affecting the data they use. Easy to fix.

- [ ] New pattern matching syntax should be documented also with `Should Match` and related keywords. Might be best to add separate section about pattern matching into introduction part of the BuiltIn docs. It seems `Should Match` documentation contains also other problems that can be fixed at the same time.

- [ ] `fnmatch.translate` doesn't seem to work with bytes on Python 3. Probably just best not to support matching bytes on Python 3 at all, but this needs to be made explicit.

All and all, the PR is great but it had surprisingly many side effects. It definitely was a good idea not to include this into minor release.

**Comment by pekkaklarck** [comment]
Tests and documentation give an impression that `[[xxx]]` would match `[xxx]`. The documentation has example

```
--test Example[[5]] # Matches tests with name Example[5].
```

and there are tests like matching `'Weird*[[name]]'` to `'Weird my[name]'`.

I don't think this statement is true. For example, the referenced test passes because `Weird*` matches `Weird my[nam`, then `[[name]` matches `e`, and finally `]` matches `]`. If the `*` would be replaces with ` my`, the test would not pass. I'll update docs and tests accordingly.

**Comment by nottyo** [comment]
Thanks for updates and great fixed @pekkaklarck

**Comment by pekkaklarck** [comment]
Thanks for the PR!

**Pull request merged**
