### PR TITLE
add new keyword : Get Regexp Matches keyword

### PR DESCRIPTION
**Pull request by MoonSungHoon**
#1985 

I made this new keyword and test case, but I cannot execute test with below command.
```
>atest\run_atests.py python atest/robot/standard_libraries/string/get_regexp_matches.robot
```
I checked another cases are all okay, but in this case "output.xml" is not exist.
```
Processing output failed: IOError: [Errno 2] No such file or directory: u'my_robotframework_path\\atest\\results\\python\\output\\get_regexp_matches\\output.xml'
```
I don't know why, please help me.

### CODE REVIEW

**Comment by robotci** [comment]
Admin, can CI be enabled?

**Comment by HelioGuilherme66** [comment]
Here is one way to run the String Test Suite:
C:\GitHub\robotframework>python atest\run_atests.py python -s String
atest\robot

It runs 104 tests in my fork.

**Comment by MoonSungHoon** [comment]
@HelioGuilherme66 Thank you for answer, but I already tried that command.
The other tests are all good. Only my new keyword tests are in trouble.

**Comment by MoonSungHoon** [comment]
Here is my cmd result
```
C:\Users\synsun\Documents\GitHub\my_robotframework>python atest\run_atests.py py
thon -s String atest/robot
...
Get Lines Matching Regexp When Input Is Empty                         | PASS |
------------------------------------------------------------------------------
Get Lines Matching Regexp When Pattern Is Empty                       | PASS |
------------------------------------------------------------------------------
Get Lines Matching Regexp Matching One Line                           | PASS |
------------------------------------------------------------------------------
Get Lines Matching Regexp Matching Some Lines                         | PASS |
------------------------------------------------------------------------------
Get Lines Matching Regexp With Case-Insensitive                       | PASS |
------------------------------------------------------------------------------
Robot.Standard Libraries.String.Get Matching Lines                    | PASS |
15 critical tests, 15 passed, 0 failed
15 tests total, 15 passed, 0 failed
==============================================================================
Robot.Standard Libraries.String.Get Regexp Matches
==============================================================================
Get Regexp Matches With No Match                                      | FAIL |
Parent suite setup failed:
Processing output failed: IOError: [Errno 2] No such file or directory: u'C:\\Us
ers\\synsun\\Documents\\GitHub\\my_robotframework\\atest\\results\\python\\outpu
t\\get_regexp_matches\\output.xml'
------------------------------------------------------------------------------
Get Regexp Matches Without Group                                      | FAIL |
Parent suite setup failed:
Processing output failed: IOError: [Errno 2] No such file or directory: u'C:\\Us
ers\\synsun\\Documents\\GitHub\\my_robotframework\\atest\\results\\python\\outpu
t\\get_regexp_matches\\output.xml'
------------------------------------------------------------------------------
Get Regexp Matches Group Regex Without Group Name                     | FAIL |
Parent suite setup failed:
Processing output failed: IOError: [Errno 2] No such file or directory: u'C:\\Us
ers\\synsun\\Documents\\GitHub\\my_robotframework\\atest\\results\\python\\outpu
t\\get_regexp_matches\\output.xml'
------------------------------------------------------------------------------
Get Regexp Matches Group Regex With Group Name                        | FAIL |
Parent suite setup failed:
Processing output failed: IOError: [Errno 2] No such file or directory: u'C:\\Us
ers\\synsun\\Documents\\GitHub\\my_robotframework\\atest\\results\\python\\outpu
t\\get_regexp_matches\\output.xml'
------------------------------------------------------------------------------
Robot.Standard Libraries.String.Get Regexp Matches                    | FAIL |
Suite setup failed:
Processing output failed: IOError: [Errno 2] No such file or directory: u'C:\\Us
ers\\synsun\\Documents\\GitHub\\my_robotframework\\atest\\results\\python\\outpu
t\\get_regexp_matches\\output.xml'

4 critical tests, 0 passed, 4 failed
4 tests total, 0 passed, 4 failed
==============================================================================
Robot.Standard Libraries.String.Remove From String
==============================================================================
Remove String                                                         | PASS |
------------------------------------------------------------------------------
Remove String Non-ASCII characters                                    | PASS |
------------------------------------------------------------------------------
Remove String Not Found                                               | PASS |
------------------------------------------------------------------------------
Remove String Multiple Removables                                     | PASS |
...
Output:  C:\Users\synsun\Documents\GitHub\my_robotframework\atest\results\python
\output.xml
Log:     C:\Users\synsun\Documents\GitHub\my_robotframework\atest\results\python
\log.html
Report:  C:\Users\synsun\Documents\GitHub\my_robotframework\atest\results\python
\report.html

C:\Users\synsun\Documents\GitHub\my_robotframework>
```

**Comment by MoonSungHoon** [comment]
After I commented
```
#Suite Setup       Run Tests    ${EMPTY}    standard_libraries/string/get_regexp_matches.robot
```
this line on atest, it works well.

**Comment by MoonSungHoon** [comment]
I understand why this test could not run. Because unwanted merge commit was added, I'll close this request, and I'll make a new.

**Pull request closed without merging**
