### PR TITLE
#ISSUES 3890 Renamed should_be_uppercase to should_be_upper_case (and …

### PR DESCRIPTION
**Pull request by miktuy**
…same with lower)

### CODE REVIEW

**Comment by miktuy** [comment]
@mnojek @pekkaklarck I hope these changes should solve problem that you discussed in corresponded issue

**Review by mnojek — APPROVED** [review]
I am not sure if there are any other places where it should be changed but this looks legit.

**Comment by miktuy** [comment]
actual master is fetched

**Review by pekkaklarck — APPROVED** [review]
Looks good! I'll merge this right away once we start RF 4.1 development.

**Pull request merged**
