### PR TITLE
2717 dictionary ignore keys

### PR DESCRIPTION
**Pull request by bbpatel2001**
Discussion
https://github.com/robotframework/robotframework/issues/2717

### CODE REVIEW

**Comment by bbpatel2001** [comment]
#2722 2717

**Comment by bbpatel2001** [comment]
@pekkaklarck any thought on this implementation ?  May be I have not followed some recommendation but you can suggest.

**Comment by bbpatel2001** [comment]
Developed new keyword that compare two dictionaries. For time being,  I have kept keyword name as  Dictionaries Should Be Equal New  Will be changed as per review comments.  Also I have compared original  v/s new keyword output.  New keyword gives exact location where key is  missing or value is not matching whereas original keyword gives long Also if you provide optional list of keys as parameter which will be  ignored while comparing dictionaries. It will not check key and key  value of ignored keys and keyword will pass if remaining keys are  matching. Please compare result of two keywords. Test name ends with New Keyword :  Used new keyword  Dictionaries Should Be Equal New Test name ends with Original Keword :  Used Original   keyword  Dictionaries Should Be Equal Example                                                                        ============================================================================== T1 Dictionaries Should Be Equal New                                   \| PASS \| ------------------------------------------------------------------------------ T2 Missing HIGHEST_CONFIDENCE In First Dict New Keyword               \| FAIL \| Mistmatch found in second dictionary:  following keys missing alert_main_list.IP.1.1.1.16.HIGHEST_CONFIDENCE ------------------------------------------------------------------------------ T2 Missing HIGHEST_CONFIDENCE In First Dict Original Keword           \| FAIL \| Following keys have different values: Key alert_main_list: {'test': 'test1', 'IP': {'1.1.1.16': {'abcd': ['I', 'Love', 'Robot', 'Framework'], '#_of_FINGERPRINTS': '1', 'EVENT_COUNT': '1', '#_of_CLUSTERS': '1', 'HIGHEST_CONFIDENCE': '49', 'IP_ADDRESS': '1.1.1.1', 'numbers': [1, 2, 3, 4, 5, 'aa']}}, 'User': {'user@test.com': {'ALERT_TRIGGERS': {'Suspicious Behavior': {'Username is an email address': '1'}, 'Suspicious Source': {'Forum Spam Blacklist': '1'}, 'Forged Source': {'Web Browser : Watson Lookup': '1'}}}}} != {'test': 'test1', 'IP': {'1.1.1.16': {'abcd': ['I', 'Love', 'Robot', 'Framework'], '#_of_FINGERPRINTS': '1', 'EVENT_COUNT': '1', '#_of_CLUSTERS': '1', 'numbers': [1, 2, 3, 4, 5, 'aa'], 'IP_ADDRESS': '1.1.1.1'}}, 'User': {'user@test.com': {'ALERT_TRIGGERS': {'Suspicious Behavior': {'Username is an email address': '1'}, 'Suspicious Source': {'Forum Spam Blacklist': '1'}, 'Forged Source': {'Web Browser : Watson Lookup': '1'}}}}} ------------------------------------------------------------------------------ T3 Missing HIGHEST_CONFIDENCE In Second Dict New Keyword              \| FAIL \| Mistmatch found in first dictionary:  following keys missing alert_main_list.IP.1.1.1.16.HIGHEST_CONFIDENCE ------------------------------------------------------------------------------ T3 Missing HIGHEST_CONFIDENCE In Second Dict Original Keword          \| FAIL \| Following keys have different values: Key alert_main_list: {'test': 'test1', 'IP': {'1.1.1.16': {'abcd': ['I', 'Love', 'Robot', 'Framework'], '#_of_FINGERPRINTS': '1', 'EVENT_COUNT': '1', '#_of_CLUSTERS': '1', 'numbers': [1, 2, 3, 4, 5, 'aa'], 'IP_ADDRESS': '1.1.1.1'}}, 'User': {'user@test.com': {'ALERT_TRIGGERS': {'Suspicious Behavior': {'Username is an email address': '1'}, 'Suspicious Source': {'Forum Spam Blacklist': '1'}, 'Forged Source': {'Web Browser : Watson Lookup': '1'}}}}} != {'test': 'test1', 'IP': {'1.1.1.16': {'abcd': ['I', 'Love', 'Robot', 'Framework'], '#_of_FINGERPRINTS': '1', 'EVENT_COUNT': '1', '#_of_CLUSTERS': '1', 'HIGHEST_CONFIDENCE': '49', 'IP_ADDRESS': '1.1.1.1', 'numbers': [1, 2, 3, 4, 5, 'aa']}}, 'User': {'user@test.com': {'ALERT_TRIGGERS': {'Suspicious Behavior': {'Username is an email address': '1'}, 'Suspicious Source': {'Forum Spam Blacklist': '1'}, 'Forged Source': {'Web Browser : Watson Lookup': '1'}}}}} ------------------------------------------------------------------------------ T4 Few Key Missing and Values Changed New Keyword                     \| FAIL \| Mistmatch found in first dictionary:  for key alert_main_list.IP.1.1.1.16.HIGHEST_CONFIDENCE value 59 is not matching: 59 != 49,  for key alert_main_list.User.user@test.com.ALERT_TRIGGERS.Suspicious Behavior.Username is an email address value 10 is not matching: 10 != 1,  following keys missing alert_main_list.IP.1.1.1.16.#_of_CLUSTERS ,  for key alert_main_list.IP.1.1.1.16.IP_ADDRESS value 1.1.1.1 is not matching: 1.1.1.1 != 1.1.2.2  Mistmatch found in second dictionary:  for key alert_main_list.IP.1.1.1.16.HIGHEST_CONFIDENCE value 49 is not matching: 49 != 59,  for key alert_main_list.User.user@test.com.ALERT_TRIGGERS.Suspicious Behavior.Username is an email address value 1 is not matching: 1 != 10,  for key alert_main_list.IP.1.1.1.16.IP_ADDRESS value 1.1.2.2 is not matching: 1.1.2.2 != 1.1.1.1,  following keys missing alert_main_list.User.user@test.com.ALERT_TRIGGERS.Forged Source.Web Browser : Watson Lookup ,  following keys missing alert_main_list.IP.1.1.1.16.EVENT_COUNT ------------------------------------------------------------------------------ T4 Few Key Missing and Values Changed Original Keword                 \| FAIL \| Following keys have different values: Key alert_main_list: {'test': 'test1', 'IP': {'1.1.1.16': {'abcd': ['I', 'Love', 'Robot', 'Framework'], '#_of_FINGERPRINTS': '1', 'EVENT_COUNT': '1', 'HIGHEST_CONFIDENCE': '49', 'IP_ADDRESS': '1.1.2.2', 'numbers': [1, 2, 3, 4, 5, 'aa']}}, 'User': {'user@test.com': {'ALERT_TRIGGERS': {'Suspicious Behavior': {'Username is an email address': '1'}, 'Suspicious Source': {'Forum Spam Blacklist': '1'}, 'Forged Source': {'Web Browser : Watson Lookup': '1'}}}}} != {'test': 'test1', 'IP': {'1.1.1.16': {'abcd': ['I', 'Love', 'Robot', 'Framework'], '#_of_FINGERPRINTS': '1', '#_of_CLUSTERS': '1', 'HIGHEST_CONFIDENCE': '59', 'IP_ADDRESS': '1.1.1.1', 'numbers': [1, 2, 3, 4, 5, 'aa']}}, 'User': {'user@test.com': {'ALERT_TRIGGERS': {'Suspicious Behavior': {'Username is an email address': '10'}, 'Suspicious Source': {'Forum Spam Blacklist': '1'}, 'Forged Source': {}}}}} ------------------------------------------------------------------------------ T5 Few Key Missing And Values Changed And Ignore One Key New Keyword  \| FAIL \| Mistmatch found in first dictionary:  for key alert_main_list.User.user@test.com.ALERT_TRIGGERS.Suspicious Behavior.Username is an email address value 10 is not matching: 10 != 1,  following keys missing alert_main_list.IP.1.1.1.16.#_of_CLUSTERS ,  for key alert_main_list.IP.1.1.1.16.IP_ADDRESS value 1.1.1.1 is not matching: 1.1.1.1 != 1.1.2.2  Mistmatch found in second dictionary:  for key alert_main_list.User.user@test.com.ALERT_TRIGGERS.Suspicious Behavior.Username is an email address value 1 is not matching: 1 != 10,  for key alert_main_list.IP.1.1.1.16.IP_ADDRESS value 1.1.2.2 is not matching: 1.1.2.2 != 1.1.1.1,  following keys missing alert_main_list.User.user@test.com.ALERT_TRIGGERS.Forged Source.Web Browser : Watson Lookup ,  following keys missing alert_main_list.IP.1.1.1.16.EVENT_COUNT ------------------------------------------------------------------------------ T5 Few Key Missing And Values Changed And Ignore One Key Original ... .No keyword to ignore key T5 Few Key Missing And Values Changed And Ignore One Key Original ... \| PASS \| ------------------------------------------------------------------------------ T6 List Mismatched At Inner Level New Keyword                         \| FAIL \| Mistmatch found in first dictionary:  for key alert_main_list.IP.1.1.1.16.HIGHEST_CONFIDENCE value 59 is not matching: 59 != 49,  for key alert_main_list.User.user@test.com.ALERT_TRIGGERS.Suspicious Behavior.Username is an email address value 10 is not matching: 10 != 1,  following keys missing alert_main_list.IP.1.1.1.16.#_of_CLUSTERS ,  for key alert_main_list.IP.1.1.1.16.IP_ADDRESS value 1.1.1.1 is not matching: 1.1.1.1 != 1.1.2.2,  for key alert_main_list.IP.1.1.1.16.numbers value [1, 2, 3, 4, 5, 'aa'] is not matching: [1, 2, 3, 4, 5, 'aa'] != [1, 2, 4, 5, 'aa']  Mistmatch found in second dictionary:  for key alert_main_list.IP.1.1.1.16.HIGHEST_CONFIDENCE value 49 is not matching: 49 != 59,  for key alert_main_list.User.user@test.com.ALERT_TRIGGERS.Suspicious Behavior.Username is an email address value 1 is not matching: 1 != 10,  for key alert_main_list.IP.1.1.1.16.IP_ADDRESS value 1.1.2.2 is not matching: 1.1.2.2 != 1.1.1.1,  for key alert_main_list.IP.1.1.1.16.numbers value [1, 2, 4, 5, 'aa'] is not matching: [1, 2, 4, 5, 'aa'] != [1, 2, 3, 4, 5, 'aa'],  following keys missing alert_main_list.User.user@test.com.ALERT_TRIGGERS.Forged Source.Web Browser : Watson Lookup ,  following keys missing alert_main_list.IP.1.1.1.16.EVENT_COUNT ------------------------------------------------------------------------------ T6 List Mismatched At Inner Level New Keyword Original Keword         \| FAIL \| Following keys have different values: Key alert_main_list: {'test': 'test1', 'IP': {'1.1.1.16': {'abcd': ['I', 'Love', 'Robot', 'Framework'], '#_of_FINGERPRINTS': '1', 'EVENT_COUNT': '1', 'HIGHEST_CONFIDENCE': '49', 'IP_ADDRESS': '1.1.2.2', 'numbers': [1, 2, 4, 5, 'aa']}}, 'User': {'user@test.com': {'ALERT_TRIGGERS': {'Suspicious Behavior': {'Username is an email address': '1'}, 'Suspicious Source': {'Forum Spam Blacklist': '1'}, 'Forged Source': {'Web Browser : Watson Lookup': '1'}}}}} != {'test': 'test1', 'IP': {'1.1.1.16': {'abcd': ['I', 'Love', 'Robot', 'Framework'], '#_of_FINGERPRINTS': '1', '#_of_CLUSTERS': '1', 'HIGHEST_CONFIDENCE': '59', 'IP_ADDRESS': '1.1.1.1', 'numbers': [1, 2, 3, 4, 5, 'aa']}}, 'User': {'user@test.com': {'ALERT_TRIGGERS': {'Suspicious Behavior': {'Username is an email address': '10'}, 'Suspicious Source': {'Forum Spam Blacklist': '1'}, 'Forged Source': {}}}}} ------------------------------------------------------------------------------ Example                                                               \| FAIL \| 11 critical tests, 2 passed, 9 failed 11 tests total, 2 passed, 9 failed  Please check the output of tests [in following archive file ] which are starting with TC TestLog_report_output.zip
--

**Comment by bbpatel2001** [comment]
please read detail reports here #2722

**Comment by pekkaklarck** [comment]
This implementation looks overly complicated. If the idea is to ignore keys, those keys should just be removed from the dictionary. No need to flatten anything. Also, I don't think ordering internal lists is a useful feature.

**Comment by bpateldg** [comment]
Actually I did not want to delete anything from dictionary because use may use same dict again in the code. 

Current keyword fails in case of unordered list.  I do agree that ordering is not required but that is optional. If set dict will be compared after ordering the list.  Use case was retriving the value from UI and store in the unordered list. compare with pre-created list. 

Anyways, please ignore if my code is not suitable. 

Thanks.

**Comment by pekkaklarck** [comment]
As I commented above, this implementation is overly complicated. The original issue is still valid, though.

**Pull request closed without merging**
