### PR TITLE
Add 'id' to attributes on keyword methods to listeners

### PR DESCRIPTION
**Pull request by vkruoso**
This aims to fix issue #2115. I was assuming that the `id` field would be calculated when calling `start_keyword` and `end_keyword`, but that does not seems to be the case. I was not able to figure it out why at this point. Do you have any thoughts about it?

Another comment: it does not look like the id field is tested at the `end_suite`, `end_teste` and `end_keyword`. Do you think this should be added?

### CODE REVIEW

**Comment by robotci** [comment]
Admin, can CI be enabled?

**Comment by pekkaklarck** [comment]
As I already commented in #2115, this PR looks really good. @robotci: enable

I would assume suite/test ids are tested somewhere too. I can take a look do they exist somewhere when I have time or you can check that too. If they don't exist, we can add them to same place as the new kw id tests. If they do, perhaps we should add some kw id tests into that location.

**Comment by robotci** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://robot.radiaatto.ri.fi//job/RobotFramework-pull-requests/103/

**Comment by pekkaklarck** [comment]
There seem to be some failures in listener tests on CI. My guess is that tests themselves just need to be updated. Listener tests are _very_ brittle and annoying to fix after smallest changes. We definitely should rewrite them to be easier to maintain.

**Comment by vkruoso** [comment]
Tests aren't passing because the keyword `id`property is always being calculated as `k1`, as if there is no parent relation established when calling the listener methods. I did not had the time to investigate this more deeply.

It looks like there is tests related to the id only in the `start_*` methods. I need to confirm this as my walk through the code was brief.

**Comment by pekkaklarck** [comment]
Yeah, getting id there correctly requires changes to code where listeners are called. I can take care of that later today or tomorrow.

**Comment by pekkaklarck** [comment]
Unfortunately keywords don't have enough context information at run time to allow calculating ids and getting such context information there would require pretty big changes. That seems to be both too much work and too risky in RF 2.9.x minor releases but can be done in RF 3.0. Good news is that we are planning to start 3.0 development already next monthn.

**Comment by vkruoso** [comment]
@pekkaklarck Its been a while now since this implementation. With the new listener interface do we get the keyword ``id`` attribute?

**Comment by pekkaklarck** [comment]
Unfortunately not. The new listener API doesn't have `start_keyword` and `end_keyword` methods exactly for the same reason that not enough context information is available. Definitely should fix that but requires changes are big. In RF 3.1 I may need to look at kw execution againg and will keep this in mind.

**Comment by vkruoso** [comment]
Will close this as the implementation was challenging, and maybe this is available in 3.x. I'm not as active using the tool right now as well. Thanks for the great work.

**Pull request closed without merging**
