### PR TITLE
Update Easter.py

### PR DESCRIPTION
**Pull request by MisterChild**
None Shall Pass !

### CODE REVIEW

**Comment by pekkaklarck** [comment]
Is the old way to embed the video outdated or why should it be changed? If there are problems, fixing them before Easter is obviously very high priority. =)

**Comment by MisterChild** [comment]
The linked video was not available anymore and youtube suggests this way of implementation. So I updated video and way of embedding. I'm glad to hear, that development priorities are fully grounded and long-sighted the same time. :-)

**Comment by pekkaklarck** [comment]
Thanks for the PR and happy Easter!

**Comment by pekkaklarck** [comment]
This change broke a test we had but I fixed it. At the same time noticed a small problem with the code and fixed that as well. The code problem was related to this:

```python
>>> len('Beginning \
...      end')
18
>>> len('Beginning'
...     'end')
12
```

**Pull request merged**
