### PR TITLE
Issue #3208: Fix for py logging formatter

### PR DESCRIPTION
**Pull request by Ka55i0peia**
Please refer to https://github.com/robotframework/robotframework/issues/3208

* apply logging formatter as stated here: https://dzone.com/articles/python-custom-logging-handler-example

### CODE REVIEW

**Comment by pekkaklarck** [comment]
This change needs some tests and possibly also an update to documentation.

**Comment by Ka55i0peia** [comment]
I don't see any test for `RobotHandler` at all!? Do you have any suggestions where to integrate?

In the stack post [1] you can see the motivation for the fix.

[1]: https://stackoverflow.com/questions/50843636/using-a-python-root-logger-with-robot-framework/56627468#56627468

**Comment by pekkaklarck** [comment]
I'm sure there are tests for this in the `atest` directory. See `atest/README rst` for details.

**Comment by pekkaklarck** [comment]
Acceptance tests for logging using `logging` are at

https://github.com/robotframework/robotframework/blob/master/atest/robot/test_libraries/logging_with_logging.robot

and test data file executed by those tests at

https://github.com/robotframework/robotframework/blob/master/atest/testdata/test_libraries/logging_with_logging.robot

and finally the library these tests use is at

https://github.com/robotframework/robotframework/blob/master/atest/testdata/test_libraries/LibUsingPyLogging.py

How all this works together is explained at [atest/README.rst](https://github.com/robotframework/robotframework/blob/master/atest/README.rst).

**Pull request closed without merging**
