### PR TITLE
improve plural_or_not

### PR DESCRIPTION
**Pull request by IlfirinPL**
#3460

### CODE REVIEW

**Comment by pekkaklarck** [comment]
- This needs a unit test.
- `count in (1, -1)` would read a bit better.

**Comment by pekkaklarck** [comment]
I was certain this util already had unit tests and it would be enough to just add some negative numbers there but apparently I was wrong. The added tests looks good but there could be another negative case like -2. I'll add it myself.

Thanks for the PR!

**Comment by pekkaklarck** [comment]
On a more detailed look tests are actually buggy! You are using strings, not numbers as an input to `plural_or_not` and it is looking at string length. The test actually fails when I run it locally. I'll fix it myself but please run tests before commit next time.

**Comment by IlfirinPL** [comment]
Thank you for feedback

**Pull request merged**
