### PR TITLE
updated-ug-style

### PR DESCRIPTION
**Pull request by Snooz82**
Updated css.

Features:

- Nicer Font
- Sidebar with TOC in 3 levels (this is depth 3 in rst file)
- If Browser to small TOC with 2 levels at the beginning
- DarkMode
- limited width for better readability
- looks good :-)
- Issue https://github.com/robotframework/robotframework/issues/4149

### CODE REVIEW

**Comment by Snooz82** [comment]
@pekkaklarck 

This PR replaces #4148 because i wanted to make these changes based on the current code base.
Still looks good, and should be in before Release of 5.0

**Comment by pekkaklarck** [comment]
Style enhancements look good. Could you clarify the reason to generate JSON spec files?

**Comment by Snooz82** [comment]
@pekkaklarck 
The json spec is for the code playground to have code completion available for standard libraries.

**Comment by Snooz82** [comment]
See https://github.com/robotframework/robotframework/tree/gh-pages/latest/libdoc

**Comment by pekkaklarck** [comment]
Ok, sounds reasonable. You may have mentioned that at some point but there was nothing about that in this PR.

Are changes in this PR enough to also include specs under gh-pages or does tasks.py there need to be updated? Is it a problem that this PR generates specs under `doc/libraries` but your example has `.../gh-pages/latest/libdoc/`?

**Comment by pekkaklarck** [comment]
If there's still work needed related to spec generation and getting them under gh-pages, perhaps it would be best to remove that part from this PR and just merge the actual UG changes.

**Comment by pekkaklarck** [comment]
The spec stuff is needed anyway so I guess it's ok to merge this.

**Pull request merged**
