### PR TITLE
Fix typo in ListenerInterface.rst

### PR DESCRIPTION
**Pull request by mkorpela**
typo fix

### CODE REVIEW

**Comment by robotci** [comment]
Admin, can CI be enabled?

**Comment by mkorpela** [comment]
Sorry robotci I speek only to humans.

**Comment by pekkaklarck** [comment]
Thanks, good catch! Think it should read "as a list", though.

**Comment by pekkaklarck** [comment]
Fixed this in 5597602 with `as a list`.

**Pull request closed without merging**
