### PR TITLE
Contribution instructions

### PR DESCRIPTION
**Pull request by guykisel**
[skip ci]

### CODE REVIEW

**Comment by robotci** [comment]
Tests passed.



Refer to this link for build results (access rights to CI server needed): 
http://robot.radiaatto.ri.fi//job/RobotFramework-pull-requests/54/Tests passed.

**Comment by robotci** [comment]
Tests passed.



Refer to this link for build results (access rights to CI server needed): 
http://robot.radiaatto.ri.fi//job/RobotFramework-pull-requests/55/Tests passed.

**Comment by laurentbristiel** [comment]
shouldn't we include a sentence about documentation? Just mentioning that when the usage of the product or a lib is modified, user documentation should be updated accordingly, and pointing people to a file with more explanation(doc/userguide/README?).

**Comment by guykisel** [comment]
That's a good idea. I'll add something about that.

**Comment by jussimalinen** [comment]
Looks good! We had a quick chat about this with @pekkaklarck and as we have written all other docs in rest, it would be better to continue with one wiki format and use the same here. Github supports also rest for contribution instructions.

As the same doc will be shown when creating a new issue, there probably should be a chapter about creating issues.

I wonder why the [skip ci] didnt work... It says in the jenkins plugin that [skip ci] should be written to "pull request body". I suppose this is not the same as the first comment at pull request?

**Comment by guykisel** [comment]
Oh, I went with markdown because https://github.com/blog/1184-contributing-guidelines only mentions markdown. I didn't know you could use rst! I'll convert it.

**Comment by guykisel** [comment]
Also, I forgot about [skip ci] initially and edited it in later.

**Comment by guykisel** [comment]
I already had a section about creating issues, but it wasn't explicitly saying so in the title. I've updated it to be more obvious.

**Comment by pekkaklarck** [comment]
Merged this PR in 388e8f2109b827daa2955903deecb85e3d67a589. I guess the PR wasn't closed because I squashed commits and thus the committed revisions weren't exactly same as here. Anyway, thanks @guykisel for the initial instructions!

**Pull request closed without merging**
